### ISSUE TITLE
Calling RayHandler.updateAndRender() confuses ScreenUtils

### ISSUE THREAD

**Issue by haimat** [libgdx/box2dlights#43] opened 2015-02-14 03:00 UTC
I take screenshots as usual in libGDX via `ScreenUtils.getFrameBufferPixmap()`, which works fine. Hoever, when I call `RayHandler.updateAndRender()` during rendering, then the screenshot only contains those assets rendered *after* this call. All other pixels in the screenshot are transparent.

What is the best way to deal with this issue?

**Comment by rinold** [comment] 2015-02-14 14:11
I've tried simple example:
```java
	...
	rayHandler.updateAndRender();
	/** BOX2D LIGHT STUFF END */
		
	Pixmap pixmap = ScreenUtils.getFrameBufferPixmap(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	batch.begin();
	batch.draw(new Texture(pixmap), 0, 0, Gdx.graphics.getWidth() / 50, Gdx.graphics.getHeight() / 50);
	batch.end();
	pixmap.dispose();
```

And got it working fine - mini-screen at center-bottom:
![image](https://cloud.githubusercontent.com/assets/2253795/6199837/53cdf2d0-b46c-11e4-82bd-bc31815520ae.png)

Need some example on which this could be reproduced.

**Comment by haimat** [comment] 2015-02-14 15:29
That's strange, I don't understand why it does work for you, but not in my case. So I have commented nearly everything out in my `render()` method, leaving only this:

	camera.update();
	spriteBatch.setProjectionMatrix(camera.combined);
	spriteBatch.begin();
	// render assets...
	spriteBatch.end();

	rayHandler.setCombinedMatrix(camera);
	rayHandler.updateAndRender();

	box2daccumulator += delta;
	while(box2daccumulator >= BOX2D_TIME_STEP) {
		box2dWorld.step(BOX2D_TIME_STEP, 6, 2);
		box2daccumulator -= BOX2D_TIME_STEP;
	}

	Pixmap pixmap = ScreenUtils.getFrameBufferPixmap(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	spriteBatch.begin();
	spriteBatch.draw(new Texture(pixmap), camera.position.x, camera.position.y);
	spriteBatch.end();

That doesn't work, I only see the normal game view, but not the pixmap. However, as soon as I comment out the line `rayHandler.updateAndRender();` the pixmap shows up in the top right quarter of the screen, as intended.

For the records, I initialize box2dlights like this:

	RayHandler.setGammaCorrection(false);
	rayHandler = new RayHandler(box2dWorld);
	rayHandler.useDiffuseLight(true);
	rayHandler.setCulling(true);
	rayHandler.setBlurNum(3);

Ohh and by the way: I am using your fork of box2dlights currently, the one you gave me recently to test the pseudo-3d feature. Maybe this has something to do with it?

**Comment by rinold** [comment] 2015-02-14 16:00
Ok... pseudo-3d might affect it... It uses frame buffers texture bindings which might produce your issue. Think I need to check for correct 'unbind' method, which I haven't found before.

BTW, if you are using stepped box2d simulation, possibly the box2dlights should be also stepped for performance reasons, like:
```java
rayHandler.setCombinedMatrix(camera);
rayHandler.render(); // do the render

box2daccumulator += delta;
while(box2daccumulator >= BOX2D_TIME_STEP) {
    box2dWorld.step(BOX2D_TIME_STEP, 6, 2);
    rayHandler.update(); // update physics
    box2daccumulator -= BOX2D_TIME_STEP;
}
```

Also just strange for me, why you update world only after the rendering? imho, the update should preceed the draw procedures, otherwise it means for current frame you render outdated world.

**Comment by haimat** [comment] 2015-02-14 16:06
Ok fine, then I will wait for your next update to box2dlights pseudo-3d and test again. Do you have any time estimation when you might have the next version ready for testing?

Ohh and thanks for your info regarding the stepped box2d simulation :-)

**Comment by rinold** [comment] 2015-02-15 14:45
You can try the box2dlights from pseudo3d branch (this, not mine :)), however it have some major API changes, but for me the screen utils worked fine:
![image](https://cloud.githubusercontent.com/assets/2253795/6203596/03a6d2f8-b53a-11e4-9fdc-d327f3467e0c.png)

If you will still face the issue, I will do some additional investigation.

For pseudo-3d you will need importing things from "box2dlight.p3d" package, and P3dLightManager is what was the rayHandler (renamed cause it not uses raycasting anymore). I will try to describe it's usage on a Wiki with details but don't know when will have time :(

**Comment by haimat** [comment] 2015-02-15 18:27
Thanks, I will have a look into your changes. One thing I already noticed from a first quick test: Using the "old" `RayHandler` I still cannot produce screenshots via the `ScreenUtils` class. Does this work for you (using `RayHandler`, **not** pseudo3d)?

**Comment by haimat** [comment] 2015-02-19 11:40
Hi, any news on this issue?
Did you had some time to experiment with my code sample?

**Comment by rinold** [comment] 2015-02-19 13:02
Nope, it seems to work fine on my machine. What libgdx version are you using?

**Comment by haimat** [comment] 2015-02-19 13:07
I am using libGDX 1.5.4, from Maven.
How can the same code lead to such different results for us? :-(

**Comment by rinold** [comment] 2015-02-19 15:40
BTW, do you have any second machine to verify this issue with your own code? To exclude the case where this issue depends on specific video drivers/configuration?

**Comment by rinold** [comment] 2015-02-19 15:41
I will try to run your complete example with the Scene on my machine with same libgdx version. But a bit later, seems my hard drive at home burned :( and I will need some time to restore all the lost data and got my machine work again.

**Comment by haimat** [comment] 2015-02-19 16:20
Ohh sorry to hear :(
Good luck with that!

**Comment by haimat** [comment] 2015-02-26 23:20
Sorry to bother you again, but did you had any luck with your hard drive?
Have you been able to run my code sample?

**Comment by dingjibang** [comment] 2015-02-27 02:55
(sorry for my bad english)
I had a same program.
On my home computer(driver is the R9280X),use box2dLight with screenUtils is not work,but it works fine on my company's computer(driver is a old Intel's HD Graphics).
After,I found when I set RayHandler.useDiffuseLight to false it works fine,but the hover light is awful

**Comment by dingjibang** [comment] 2015-02-27 11:27
just now I tried to update my game libgdx version(from 1.5.0 to 1.5.4)
But the problem still exists
_(:3」∠)_ohhhh……

**Comment by rinold** [comment] 2015-02-27 12:11
I've got the new one and setting up the environment, but still wasn't able to recover some important data from old :)

BTW, I've missed some important question - on which OS you are facing this issue?

**Comment by dingjibang** [comment] 2015-02-27 12:14
win7 sp1 (home and company 's computer)

**Comment by rinold** [comment] 2015-02-27 12:31
Ohh.. I can't even imagine what is happening now :( Just as a guess, looking at the box2dlights internals code, could you check following:
```java
        ...
        rayHandler.updateAndRender();

        Pixmap pixmap = ScreenUtils.getFrameBufferPixmap(0, 0, Gdx.graphics.width, Gdx.graphics.height);
        Texture tex = new Texture(pixmap);
        tex.bind(0); // <-- Does the issues still exists with this code?
        spriteBatch.begin();
        spriteBatch.draw(tex, 0, 0, Gdx.graphics.width * 0.5f, Gdx.graphics.height * 0.5f);
        spriteBatch.end();
        ...
```

And also does the ScreenUtils.getFrameBufferTexture(...) have the same issue?

**Comment by dingjibang** [comment] 2015-02-27 12:43
no……
whatever I add or not add tex.bind(0)
the issues still exists_(:3」∠)_

sorry the CHINESE network is too bad I can't upload result image
the code is same as your example_(:3」∠)_

**Comment by dingjibang** [comment] 2015-02-27 12:47
http://blog.rpsg-team.com/?p=187
here are results

**Comment by dingjibang** [comment] 2015-02-27 15:59
just now I tried to use vmware ubuntu kylin system and there is no issues!
The same code and hardware but differences os are differences result……

BUT my company's PC also use win7 system,eh there maybe some differences
I will give you more info tomorrow

**Comment by haimat** [comment] 2015-02-28 23:54
I am using Linux btw.

**Comment by rinold** [comment] 2015-03-02 09:41
It's hard to understand while I can't reproduce it :( as @dingjibang said that it works when diffuse light is disabled - that means the issue might be caused by FBO and diffuse shader, if so it might be not the box2dlights issue but some issue with libgdx stuff it uses. What I can suggest currently - is to create the  minimal sample after which the ScreenUtils fails to create screenshot - basing on box2dlights LightMap render method code but with all unnecessary code removed and possibly replaced with some dummy rendering stuff. Looking currently think we could try to reproduce the issue with following scenarios:

1. Create the shader manually by calling:
```java
    ShaderProgram shader = DiffuseShader.createShadowShader();
    // do some draw like in LightMap.render with this shader
    ...
    // Try to grab the screenshot
```

2. Do the previous step but adding usage the FBO as in LightMap

If one of this small scenarios is failing then we can go with this results to forum/issue tracker and got it solved. Otherwise I'll keep looking for a machine on which I could reproduce it and will experiment with it by myself.

**Comment by haimat** [comment] 2015-03-02 19:11
Thanks for your reply. I am sorry though, I have not much experience and knowledge with all this shader and FBO stuff, so I don't really know what to do know.

Could you please be so kind and tell me exactly what you want me to do now? Thanks!

**Comment by dingjibang** [comment] 2015-03-03 02:08
me too:(

**Comment by rinold** [comment] 2015-03-03 12:25
It's ok, don't worry :) I just need some free time to create some minimal samples at work... I will post them here when done.

**Comment by dingjibang** [comment] 2015-03-03 12:28
thanx

**Comment by haimat** [comment] 2015-03-03 12:54
Super, thank you very much!

**Comment by szszss** [comment] 2015-03-06 05:07
I tried @haimat 's example (with a few modifications, of course), and "it opened a gate of new world for me" because it was the first time in my life that SEEING A INTEL INTEGRATED GRAPHICS PROCESSOR WORKS BETTER THAN NVIDIA DEDICATED GRAPHICS CARD. When the Intel managed to snap a wrong picture (the screenshot has lots of blank), the Nvidia was silent totally.
Anyway, I noticed that when Nvidia card snapped screenshots without light rendering, it can snapped all opaque objects (in another word, all the screen excluding where is blank), and I also noticed that the *ScreenUtils* always snaps a screenshot with Alpha, which is impossible displayed in screen. So I copy a *getFrameBufferPixmap* to my testing class, modifying the format of pixmap from *RGBA8888* to *RGB888*, and modifying the format of *glReadPixels* from *RGBA* to *RGB*. Eventually, it works on my laptop with both Intel and Nvidia card.
I guess there is something violates the specification of OpenGL in the shading of light, and it makes the card giving up to read pixels with all four channels. The using of FrameBuffer seems having no problem. Should the shaders of Box2Lights clamp the Alpha of fragment? 
And there is also a silver bullet if your game only works in desktop and the solution in above is invalid: change the reading buffer. In the default state, glReadPixels only read from backend buffer (you have already known the double buffer, right?). However, you can use *GL11.glReadBuffer(GL11.GL_FRONT)* to let it read from front buffer. This is real "What You See Is What You Get", but it can only get the screenshot of past one frame, not this frame. And you can't draw the screenshot in your screen in real time (you know why, hehe).

**Comment by dingjibang** [comment] 2015-03-06 05:29
thank u, I'll try

**Comment by rinold** [comment] 2015-03-06 08:57
@szszss thanks for your investigation! :) Actually, I'm not an expert in everything you described, but:
>Anyway, I noticed that when Nvidia card snapped screenshots without light rendering, it can snapped all opaque objects (in another word, all the screen excluding where is blank), and I also noticed that the ScreenUtils always snaps a screenshot with Alpha, which is impossible displayed in screen. So I copy a getFrameBufferPixmap to my testing class, modifying the format of pixmap from RGBA8888 to RGB888, and modifying the format of glReadPixels from RGBA to RGB. Eventually, it works on my laptop with both Intel and Nvidia card.

Might this alpha channel problems be caused by box2dlights render method leaves with the GL_BLEND disabled? And also as @dingjibang mentioned that this happens for diffuse lights, where in shader really nothing is done with alpha channel?
How it works if in "DiffuseShader.java" fragment shader we add setting of the alpha?:
```java
				+ "{\n" //
				+ "gl_FragColor.rgb = (ambient.rgb + texture2D(u_texture, v_texCoords).rgb);\n" //
				+ "gl_FragColor.a = ambient.a;" // <-- add settings of alpha
					+ "}\n";
```

**Comment by szszss** [comment] 2015-03-06 11:57
Hmmm... I'm not sure does it caused by blend. However, I built a modified demo which tries to draw a screenshot of left half side in the right half side, and the screenshot was snapped by *ScreenUtils*. As was expected, it didn't draw. And then I added setting of the alpha in the DiffuseShader, and this time it worked.

![pic](https://cloud.githubusercontent.com/assets/3639840/6524875/9340553e-c439-11e4-97ad-c8597c3e9191.png)
(Figure above: Without setting.    Figure below: With setting.)

(However, in my computer I didn't used "gl_FragColor.a = ambient.a;", because the screenshot will became transparent. I used "*gl_FragColor.a = 1.0;*". I haven't too much understandings about the shading pipeline of Box2dLights, so the choice is yours. Just don't make the alpha undefined, neither the drivers nor specification like this situation.)

(Although Gaussian hasn't setting of the alpha, too, it isn't the last step, and the ShadowShader and WithoutShadowShader can fix its mistake.)

**Comment by rinold** [comment] 2015-03-06 12:28
Great! Seems we found the root cause :) Using 1.0 is absolutely better than ambient, but still I need to think about what is actually correct here.

**Comment by haimat** [comment] 2015-03-06 12:39
Sounds great, thanks for your analysis and efforts guys!
I am looking forward to testing any update you come up with.
Please let me know if I can help you in any way.

**Comment by rinold** [comment] 2015-03-07 14:36
May be it will be correctly to use the alpha of sampler texture, but I've leaved the 1.0 value cause haven't find the real usage benefits of it. Updated both branches, should be fixed now.

**Closed** 2015-03-07 14:39 UTC
Labels: bug, pseudo3d

**Comment by haimat** [comment] 2015-03-07 16:21
Great, thanks. Can I get the update from Maven already in a new box2dlights version?
